apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # Read from the cluster-config ConfigMap
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            env: production
          - cluster: dev-cluster
            url: https://86f455be-be3d-432e-9b03-c363b2fa6829.ap-south-2-gw.linodelke.net:443
            env: development
          - cluster: dev-cluster
            url: https://86f455be-be3d-432e-9b03-c363b2fa6829.ap-south-2-gw.linodelke.net:443
            env: sit
          - cluster: dev-cluster
            url: https://86f455be-be3d-432e-9b03-c363b2fa6829.ap-south-2-gw.linodelke.net:443
            env: uat
  template:
    metadata:
      name: "{{cluster}}-apps"
      labels:
        environment: "{{env}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/zdk/argocd-apps.git
        targetRevision: HEAD
        path: apps/{{cluster}}
      destination:
        server: "{{url}}"
        namespace: "{{env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
